# Generated by Django 4.1.1 on 2022-09-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='color',
            field=models.CharField(choices=[('blue', 'blue'), ('green', 'green'), ('orange', 'orange')], max_length=20, null=True),
        ),
    ]
