# Generated by Django 4.1.1 on 2022-09-12 10:08

from django.db import migrations, models
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.IntegerField(default=tasks.models.get_next_id, primary_key=True, serialize=False, unique=True),
        ),
    ]
